### PR TITLE
updating kubescape support

### LINKED ISSUE #29: Integrate Kubescape with ValidKube
https://github.com/armosec/kubescape

### PR DESCRIPTION
**Pull request by dwertent**
After testing the first integration we found some issues since the file seems to be shared by all users, this caused an override of the file while reading/writing. 
We updated the file name so it will generate a new name each time, and we also delete the file after reading the content.
Also, we updated the output display so it will be more user-friendly.

image

Resolve #29

### CODE REVIEW

**Comment by dwertent** [comment]
@nirsht

**Review by nirsht — COMMENTED** [review]
In general LGTM, can you change the version in the Dockerfile so it won't pull the latest? We don't want the parsing here to break in future versions.

**Comment by nirsht** [comment]
@dwertent

**Comment by dwertent** [comment]
@nirsht Done

**Review by nirsht — APPROVED** [review]

**Pull request merged**
