### PR TITLE
feat: add trivy image and sbom functionality

### PR DESCRIPTION
**Pull request by dirien**
Hi,

This PR adds support for Image and SBOM scan via trivy.

image

Do increase the render performance of the json output from Trivy (its much) I changed the editor to Codemirror with a custom theme to fit the old color schema. Now you have line numbers and search function too!

Hope you folks like it and feedback is welcome.

### CODE REVIEW

**Comment by dirien** [comment]
Hi,

short ping for the PR :)

**Review by nirsht — COMMENTED** [review]
Hi @dirien LGTM, please Add the project info in the readme 
+ resolve the conflicts

**Comment by dirien** [comment]
Hi @nirsht, thanks for reviewing. 

Since the initial PR, it happend a lot at Trivy. So we can now choose to create the SBOM with cylconedx or spdx.

I decided now for cylconedx as I think the UI gets a little bit overloaded now 😢. 

Looking forward for you feedback.

**Comment by nirsht** [comment]
HI @dirien that's OK, let's remove the title of `Image (Trivy)`.

**Comment by dirien** [comment]
> HI @dirien that's OK, let's remove the title of `Image (Trivy)`.

hi @nirsht, which part of the title you mean?

**Comment by nirsht** [comment]
> > HI @dirien that's OK, let's remove the title of `Image (Trivy)`.
> 
> hi @nirsht, which part of the title you mean?

I mean remove the tab of `Image (Trivy)` so the only tab that is added here is `SBOM (Trivy)`. Isn't the tab of `Secure (Trivy)` doing the work of `Image (Trivy)` tab ?

**Comment by dirien** [comment]
Secure Trivy is doing the config scan of the manifest

**Comment by nirsht** [comment]
@dirien so let's drop `Image (Trivy)` for now so the tabs won't be overloaded. Until we will find some way to make the tabs more extendable.

**Comment by dirien** [comment]
ahh okay got it @nirsht 😅 

Done! 👍

**Review by nirsht — APPROVED** [review]

**Pull request merged**
